### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by somepaulo** [comment]
Thank you for the contribution.
I've simplified the centered positions descriptions to make them shorter to better fit in the dropdown.

**Comment by Vistaus** [comment]
I don't see any difference.

**Comment by somepaulo** [comment]
I changed 'Klok aan linkerzijde' to 'Klok links' and so on. The update has just been approved on EGO.

**Comment by Vistaus** [comment]
Sadly not the best translation, but it'll do.

**Comment by somepaulo** [comment]
Yeah, I know, it's not the best description in any language, but that's the kind of compromise localisation and fitting into design restrictions requires sometimes.

The centered positions are actually uncentered if you look from the point of view of those who wanted the actual clock to remain centered in the early days of the extension, not the whole content of the central box, which happens by default. So it's confusing to accurately describe the positions and difficult to do so in a concise way that fits the design.

**Comment by Vistaus** [comment]
> Yeah, I know, it's not the best description in any language, but that's the kind of compromise localisation and fitting into design restrictions requires sometimes.

Not really. I've been a professional translator for years and I've also done an endless amount of FOSS translations for years (and are still maintaining the majority of them) and it's very rare to encounter something like this.

(And especially someone not familiar with the language changing it without consulting the translator.)

**Comment by somepaulo** [comment]
I'm sorry for not consulting you before making the translation changes. I don't think these particular terms are too important for a good user experience. But you're welcome to propose a change that wouldn't be as long as the original translation. I'm happy to merge that.

In my 25 years of professional translation and localisation experience with six languages, I've had numerous cases where compromises had to be made with 'long' languages, like Russian, that needed to fit in a tight interface.

While English is my only active Germanic language, I've had quite some exposure to Dutch and a bit of German too. I understand that not even the English 'Clock left centered' is perfect. And this holds true for Dutch, as you confirm, and very likely for German as well. Still, it kinda works, especially with the visual aid of actually seeing the indicator (and clock) change position.

I guess, my point is this is not about linguistic purity, but about usability. Does the user understand what the options mean? Do we need to go into more detail? I'd say yes and no respectively, but I'm happy to revise my position.

**Pull request merged**
